physics:
  enabled: true # disabling physics allows manual control over state via API
  dt: 0.004 # [s] (250 Hz, matches Gazebo default)
  force_cpu: false # if false, GPU is selected if available
  rtf: 0 # Throttle to this real-time factor. 0 disables throttling.
api:
  enabled: false # enable gRPC API for external control
  port: 4561 # gRPC server port
sensors:
  gps:
    init:
      lat: 47.747944 # [deg]
      lon: -122.163917 # [deg]
      alt: 5.02 # [m AMSL]
  mag:
    offset: [0.0, 0.0, 0.0] # [Gauss] hard-iron bias added to mag readings
